version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
  user-service:
    image: "webdevtoolsandtech/user-service"
    environment:
    - REDIS_ADDRESS=redis:6379
    - PORT=80
  currency-calculator:
    build: .
    environment:
    - PORT=5000
  currency-frontend:
    image: "webdevtoolsandtech/currency-frontend"
  currency-backend:
    image: "webdevtoolsandtech/currency-backend"
    environment:
    - PORT=80
    - REDIS_ADDRESS=redis:6379
    - SESSION_SECRET=Ogoyug87yIUgus
    - USER_SERVICE_ADDRESS=user-service:80
    - FRONTEND_ADDRESS=currency-frontend:80
    - CALCULATOR_ADDRESS=currency-calculator:5000
    ports:
     - "80:80"
